const express = require('express');
const path = require('path');

const logger = require('morgan');

const port = process.env.PORT || 8080;
const host = process.env.HOST || '0.0.0.0';

const app = express();

app.use(logger('combined'));

// the __dirname is the current directory from where the script is running
app.use(express.static(path.join(__dirname, '/dist')));

// send the user to index html page inspite of the url
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, '/dist/index.html'));
});

app.listen(port, host, () => console.log(`Listening on ${host}:${port}`));

/**
 * This file contains code to run a simple static html server. For example,
 * it could serve any of our html/js bundles generated by webpack/storybook/etc.
 */
